### ISSUE TITLE
`sanetime`+`dateutil` error

### ISSUE THREAD

**Issue by danmoser** [jiko/NBAonESPN#1]
The ESPN scrapper is giving me the following error:

```$ python espn_ics.py 
Traceback (most recent call last):
  File "/home/user/espn_ics.py", line 4, in <module>
    from sanetime import time, delta
  File "/home/user/.local/lib/python3.9/site-packages/sanetime/__init__.py", line 1, in <module>
    from .sanetime import SaneTime,sanetime,time,nsanetime,ntime
  File "/home/user/.local/lib/python3.9/site-packages/sanetime/sanetime.py", line 4, in <module>
    from dateutil import parser
  File "/home/user/.local/lib/python3.9/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax
```

- python-dateutil               1.5
- sanetime                      4.2.3

**Comment by danmoser** [comment]
I believe `sanetime` is using a *very* old `dateutil` version...
